female(pam). 
female(ann). 
female(liz). 
female(angela). 
female(sue). 
female(mary). 
male(pat). 
male(bob). 
male(tom). 
male(jim). 
male(dave).

parent(bob,mary). 
parent(bob,ann). 
parent(bob,pat). 
parent(bob,sue). 
parent(tom,liz). 
parent(tom,bob).
parent(pam,bob). 
parent(sue,dave). 
parent(sue,angela). 
parent(pat,jim).
